# Service
apiVersion: v1
kind: Service
metadata:
  name: reactjs-service
spec:
  selector:
    app: reactjs
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3001
      nodePort: 30080
  type: NodePort