version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: infra
      POSTGRES_DB: infra
    container_name: infra
    volumes: 
      - ./postgres:/var/lib/postgresql/data

volumes:
  postgres: